name: Chat gay BeurOnline
favicon: null
layout_spectrum: 0.83276
typography_spectrum: 0.916492534102872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9f9387'
    - '#786a5f'
    - '#281c2a'
    - '#c6b9a9'
    - '#fffbf8'
  brandStrength: 0.3125
  lightness: 0.5361946453340352
  saturation: 0.6831044394057244
  rhythmicContrast: 0.2639943507965654
purpose: []
